export const SET_PICKUP_SEARCH_RESULT = 'SEARCH ACTION SET PICK UP SEARCH RESULT';
export const SET_DROP_SEARCH_RESULT = 'SEARCH ACTION SET DROP SEARCH RESULT';
export const SET_PICKUP_SEARCH_KAYAK_RESULT = 'SEARCH ACTION SET PICKUP SEARCH KAYAK RESULT';
export const SET_DROP_SERACH_KAYAK_RESULT = 'SEARCH ACTION SET DROP SEARCH KAYAK RESULT';